# Generated by Django 4.0.3 on 2022-04-12 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='time_create',
            new_name='created_at',
        ),
    ]
